---
logs:
  level: DEBUG
  token: ~
cuff:
  appId: fmriprep_LTS-20.2.1
  name: fmriprep_test
  archive: true
  archivePath: testing/actor-fmriprep-20.2.1
  archiveSystem: a2cps.home.heejung
  inputs:
    BIDS_DIRECTORY: agave://a2cps.storage.public/a2cps_openneuro_testdata/
  parameters:
    PARTICIPANT_LABEL: sub-01
    OUTPUT_DIR: outputs
    HEAD_MOTION: 9
    ICA_AROMA_USE: false
    ICA_AROMA_DIMENSIONALITY:
    CIFTI_OUTPUT: --cifti-output 91K
    IGNORE_FIELD_MAPS: false
    IGNORE_SLICE_TIMING: false
    DUMMY_SCANS:
    FD_SPIKE: 0.9
  notifications:
    -
      event: FINISHED
      url: your@email.com
rest:
  appId: fmriprep_LTS-20.2.1
  name: fmriprep_test
  archive: true
  archivePath: testing/actor-fmriprep-20.2.1
  archiveSystem: a2cps.home.heejung
  inputs:
    BIDS_DIRECTORY: agave://a2cps.storage.public/a2cps_openneuro_testdata/
  parameters:
    PARTICIPANT_LABEL: sub-01
    OUTPUT_DIR: outputs
    HEAD_MOTION: 9
    ICA_AROMA_USE: true
    ICA_AROMA_DIMENSIONALITY:
    CIFTI_OUTPUT: --cifti-output 91K
    IGNORE_FIELD_MAPS: false
    IGNORE_SLICE_TIMING: false
    DUMMY_SCANS:
    FD_SPIKE: 0.3
  notifications:
    -
      event: FINISHED
      url: your@email.com
